// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIgflmyCwtg9_4Nduz6JCpELyIpEJ18zA',
    appId: '1:980242297725:web:1f45266cb88b18813c1214',
    messagingSenderId: '980242297725',
    projectId: 'trdltoolapp',
    authDomain: 'trdltoolapp.firebaseapp.com',
    databaseURL: 'https://trdltoolapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'trdltoolapp.firebasestorage.app',
    measurementId: 'G-9NSWGM5G4D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDr1P36PJgAt3vOJAnhEGjvfxZ_j60d6dA',
    appId: '1:980242297725:android:5fbe7c551031d2143c1214',
    messagingSenderId: '980242297725',
    projectId: 'trdltoolapp',
    databaseURL: 'https://trdltoolapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'trdltoolapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdAPW14rbPXrmh8cxdiXz4LD1GONh0o1M',
    appId: '1:980242297725:ios:3a9d15085fae11943c1214',
    messagingSenderId: '980242297725',
    projectId: 'trdltoolapp',
    databaseURL: 'https://trdltoolapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'trdltoolapp.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.trdltool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdAPW14rbPXrmh8cxdiXz4LD1GONh0o1M',
    appId: '1:980242297725:ios:3a9d15085fae11943c1214',
    messagingSenderId: '980242297725',
    projectId: 'trdltoolapp',
    databaseURL: 'https://trdltoolapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'trdltoolapp.firebasestorage.app',
    iosBundleId: 'dev.plotsklapps.trdltool',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBIgflmyCwtg9_4Nduz6JCpELyIpEJ18zA',
    appId: '1:980242297725:web:4fab1ec4b48b09eb3c1214',
    messagingSenderId: '980242297725',
    projectId: 'trdltoolapp',
    authDomain: 'trdltoolapp.firebaseapp.com',
    databaseURL: 'https://trdltoolapp-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'trdltoolapp.firebasestorage.app',
    measurementId: 'G-CSC3067FPW',
  );

}